version: '3.7'

services:
    postgres:
        build: .docker/postgres
        container_name: dashboad-postgres
        restart: always
        tty: true
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=DEVELOPMENT

volumes:
    postgres_data:
